const CART_ACTION_TYPES = {
  CHECKOUT_ORDERS: 'CHECKOUT_ORDERS',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
};

const PRODUCTS_ACTION_TYPES = {
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
};

const ActionTypes = {
  ...CART_ACTION_TYPES,
  ...PRODUCTS_ACTION_TYPES,
};

export default ActionTypes;
