const CART_ACTION_TYPES = {
  SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS',
  SET_CART_ITEMS: 'SET_CART_ITEMS',

  PUSH_PRODUCT_TO_CART: 'PUSH_PRODUCT_TO_CART',
  ADD_ITEM_QUANTITY: 'ADD_ITEM_QUANTITY',
};

const PRODUCTS_ACTION_TYPES = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  DECREMENT_PRODUCTS_INVENTORY: 'DECREMENT_PRODUCTS_INVENTORY',
};

const ActionTypes = {
  ...CART_ACTION_TYPES,
  ...PRODUCTS_ACTION_TYPES,
};

export default ActionTypes;
